# Generated by Django 3.0.1 on 2019-12-21 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='name',
            new_name='dataset_name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='img_url',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='private',
        ),
        migrations.RemoveField(
            model_name='image',
            name='dataset',
        ),
        migrations.AddField(
            model_name='dataset',
            name='dataset_description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=255)),
                ('label_description', models.CharField(max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vision.Dataset')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vision.Label'),
        ),
    ]
