# Generated by Django 3.0.1 on 2019-12-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='no-img.jpg', upload_to='./'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
