# Generated by Django 3.0.1 on 2019-12-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20191229_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='img_file_path',
            field=models.CharField(default='url', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='img_url',
            field=models.CharField(default='uploaded', max_length=255),
        ),
    ]
